name: Fastlane
on: [push]
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android beta'
          skip-tracking: false

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'ios beta'
          skip-tracking: false
